### ISSUE TITLE
[Feature] Need to add template for issues.

### ISSUE THREAD

**Issue by asmitsirohi** [akanshSirohi/ShareX-Plugins#3]
Currently, in the project, there is no template for issues. Because of that fellow contributors find it challenging to create an issue in more detailed way.
Also, with the template, it is very easy for repo maintainers to understand the requests of the community members.

**Comment by asmitsirohi** [comment]
@akanshSirohi Please assign this to me.

**Comment by akanshSirohi** [comment]
@asmitsirohi Sure, you can work on it. I am assigning it to you.
