### ISSUE TITLE
[Feature Request] Need to add template for pull request.

### ISSUE THREAD

**Issue by asmitsirohi** [akanshSirohi/ShareX-Plugins#5]
**Is your feature request related to a problem? Please describe.**
Currently, in the project, there is no template for pull requests. Because of that fellow contributors find it challenging to create a pull request in a more detailed way.

**Describe the solution you'd like**
I will add the pull request template, which will be used whenever any contributor tries to create a pull request.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by asmitsirohi** [comment]
@akanshSirohi Please assign this to me.

**Comment by akanshSirohi** [comment]
Sure!
