### ISSUE TITLE
[Feature Request] Need to add code of conduct.

### ISSUE THREAD

**Issue by asmitsirohi** [akanshSirohi/ShareX-Plugins#7]
**Is your feature request related to a problem? Please describe.**

Currently, in the project, there is no guideline for writing code. So it is challenging for the new contributors to write code in the required structure so It would become difficult for the maintainers to review it, or maintain the repository.

**Describe the solution you'd like**

I will add the Code of Conduct as a .md file.

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by asmitsirohi** [comment]
@akanshSirohi Please assign this to me.

**Comment by akanshSirohi** [comment]
Sure @asmitsirohi
